echo "FROM registry.k8s.io/ingress-nginx/controller:v1.6.4" > ingress-nginx-controller-v1.6.4
echo "FROM registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343" > kube-webhook-certgen-v20220916-gd32f8c343
